#PUBLISH_RELEASE
name: PUBLISH_RELEASE

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
      RELEASE_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run assembleRelease
        run: ./gradlew BNAppAuth_Android:clean assembleRelease

      - name: Run publish
        run: ./gradlew BNAppAuth_Android:publish
